### ISSUE TITLE
Need assistance building the samples - 

### ISSUE THREAD

**Issue by luisefigueroa** [Azure/azure-event-hubs#7] opened 2015-11-17 18:05 UTC
Hello, 

I am following the instructions in /raspberrypi_raspbian_setup.md to build the samples in a Raspberry PI 2 running Raspbian Jessie September 2015. 

When I get to the step where I issue the following command: 

~/azure-event-hubs/c/eventhub_client/samples/send/linux/send

I get the following error:

****************************************** Begin Error ***********************************************
pi@raspberrypi ~ $ ~/azure-event-hubs/c/build_all/linux/build.sh
In common/build/linux
  make -f makefile.linux all
In eventhub_client/build/linux
  make -f makefile.linux all
../../src/eventhubclient_ll.c: In function ‘GenerateMessagePayload’:
../../src/eventhubclient_ll.c:622:21: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 7 has type ‘size_t’ [-Werror=format=]
                     LogError("The message (%lu bytes) exceeds the limit currently allowed on the link.\r\n", totalSize);
                     ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors
make[1]: *** [../../src/eventhubclient_ll.o] Error 1
make: *** [all] Error 2

********************************************* End Error *************************************

Any thoughts as to what could be the cause?

Thanks in advance,
Luis Figueroa

**Comment by eric11144** [comment] 2015-12-23 13:35
Dear luisefigueroa:

Do you have any solution to solve this problem??
Because I have the same problem,but I dont have any solution to fix it.

thanks

by eric

**Comment by luisefigueroa** [comment] 2015-12-23 13:45
Hi Eric,

No, I didn't find a solution. Hopefully someone can share some light soon. One thought I had was to re-flash my PI with the previous version of Raspbian and try again but I have not gotten around to do that. 

Please comment here if you find a solution. 

Thanks!
Luis Figueroa

**Comment by dcristoloveanu** [comment] 2016-02-20 01:17
This part of the code has now been rewritten and a new release is out.
Closing this issue as it is also rather old (sorry for the huge delay).
Please re-open it if the problem is still there.

Thanks,
/Dan

**Closed by dcristoloveanu** 2016-02-20 01:17 UTC
